#!/usr/bin/env ruby
# post-receive

developer_deploy_to_dir = ''
master_deploy_to_dir = ''

def deploy(branch, to, deploy_to_dir, branch_name)
	if (branch =~ /#{branch_name}$/)
		deploy_to_dir = File.expand_path(deploy_to_dir)
		require 'fileutils'
		FileUtils::mkdir_p deploy_to_dir unless File.exists?(deploy_to_dir)
		`GIT_WORK_TREE="#{deploy_to_dir}" git checkout -f #{branch_name}`
		puts "DEPLOY: #{branch_name}(#{to}) copied to '#{deploy_to_dir}'"
		exit
	end
end

# 1. Read STDIN (Format: "from_commit to_commit branch_name")
from, to, branch = ARGF.read.split " "

deploy(branch, to, developer_deploy_to_dir, 'developer')
deploy(branch, to, master_deploy_to_dir, 'master')

puts "Received branch #{branch}, not deploying."
